#!/bin/bash -e

function packages_setup {
  apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D || true
  echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
  apt-get update
  apt-get install -y docker-engine=1.11.1-0~trusty nodejs npm python-pip python-dev python3-dev python-pytest python-yaml
  pip install setuptools requests mock mockito slackclient Jinja2 tabulate
}

function docker_setup {
  #sudoless docker
  gpasswd -a vagrant docker
  #add insecure registry
  sed -i '/#DOCKER_OPTS=/c\DOCKER_OPTS="--insecure-registry registry.roger.dal.moz.com:5000"' /etc/default/docker
  service docker restart
}


# main

packages_setup
docker_setup
