#!/usr/bin/env bash

set -ex

function packages_setup {
  apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D || true
  echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
  apt-get update
  apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine=1.11.1-0~trusty
  apt-get install -y docker-engine=1.11.1-0~trusty nodejs npm python-pip python-dev python3-dev python-pytest python-yaml
  pip install setuptools requests mock mockito slackclient Jinja2 tabulate statsd slackweb
}

function docker_setup {
  #sudoless docker
  gpasswd -a vagrant docker
  #add insecure registry
  sed -i '/#DOCKER_OPTS=/c\DOCKER_OPTS="--insecure-registry registry.roger.dal.moz.com:5000"' /etc/default/docker
  service docker restart
}



function set_env_vars {
  local bash_path=/home/vagrant/.bash_profile
  touch "$bash_path"
  chown vagrant:vagrant $bash_path
  if ! grep 'ROGER_USER_PASS_PROD' "$bash_path"; then
    cat <<'EOF' >> "$bash_path"

    echo "Example: firstname.lastname"
    read -p 'ROGER_USER: ' uservar
    read -p 'ROGER_USER_PASS_DEV: ' passdevvar
    read -p 'ROGER_USER_PASS_STAGE: ' passstagevar
    read -p 'ROGER_USER_PASS_PROD: ' passprodvar

    export ROGER_USER="$uservar"
    export ROGER_USER_PASS_PROD="$passprodvar"
    export ROGER_USER_PASS_STAGE="$passstagevar"

    export ROGER_CONFIG_DIR="/home/vagrant/roger-cli/config/"
    export ROGER_SECRETS_DIR="/home/vagrant/roger-cli/secrets"
    export ROGER_USER_PASS_DEV="$passdevvar"
    export ROGER_COMPONENTS_DIR="/home/vagrant/roger-cli/components"
    export ROGER_TEMPLATES_DIR="/home/vagrant/roger-cli/templates"

EOF
  fi
}


# main
set_env_vars
packages_setup
docker_setup
